### ISSUE TITLE
`duplicate symbol '_OBJC_CLASS_$_RCTClipboard' in` when building in iOS

### ISSUE THREAD

**Issue by beetlebum** [react-native-community/react-native-clipboard#13]
## Environment
System:
    OS: macOS 10.15.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 76.47 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.12.0 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 5.1.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5977832
    Xcode: 11.2.1/11B53 - /usr/bin/xcodebuild
  npmPackages:
    react: ^16.10.2 => 16.11.0 
    react-native: ^0.61.2 => 0.61.4

## Platforms
iOS

## Versions
Latest

## Description
After installing react-native-clipboard on a RN 0.61.4 project, I get the following error when building for iOS:

```duplicate symbol '_OBJC_CLASS_$_RCTClipboard' in:
    /Users/diegolopez/Code/GitHub////ios/build/BetterHalf/Build/Products/Debug-iphonesimulator/React-Core/libReact-Core.a(RCTClipboard.o)
    /Users/diegolopez/Code/GitHub////ios/build/BetterHalf/Build/Products/Debug-iphonesimulator/react-native-clipboard/libreact-native-clipboard.a(RCTClipboard.o)
duplicate symbol '_OBJC_METACLASS_$_RCTClipboard' in:
    /Users/diegolopez/Code/GitHub////ios/build/BetterHalf/Build/Products/Debug-iphonesimulator/React-Core/libReact-Core.a(RCTClipboard.o)
    /Users/diegolopez/Code/GitHub////ios/build/BetterHalf/Build/Products/Debug-iphonesimulator/react-native-clipboard/libreact-native-clipboard.a(RCTClipboard.o)
ld: 2 duplicate symbols for architecture x86_64```

It seems like there's a clash between this library and react-core.

**Comment by ekzotech** [comment]
The same for me here.
react-native 0.61.5
react-native-clipboard 1.0.1

Can't build iOS app, build fails with error about duplicate symbols.
Is there any ways to fix this?

**Comment by pakkibokati2012** [comment]
I am still not able to build the project.

**Comment by Naturalclar** [comment]
@pakkibokati2012 Sorry about that!
The fix has been made, but the package is not published yet.
I'm working with the community to get this published whenever possible.
Mean while, you can install the package directry from the github by setting the package below in your `package.json`

```
"@react-native-community/react-native-clipboard":"react-native-community/react-native-clipboard#master"
```

Cheers :)
