### ISSUE TITLE
IOS is still error

### ISSUE THREAD

**Issue by jiandaoshou-adwald** [react-native-community/react-native-clipboard#20]
Build/Products/Debug-iphonesimulator/react-native-clipboard/libreact-native-clipboard.a(RCTClipboard.o)
ld: 2 duplicate symbols for architecture x86_64

nom install is still not right 

require 'json'

package = JSON.parse(File.read(File.join(__dir__, 'package.json')))

Pod::Spec.new do |s|
  s.name         = "react-native-clipboard"
  s.version      = package['version']
  s.summary      = package['description']
  s.license      = package['license']

  s.authors      = package['author']
  s.homepage     = package['homepage']
  s.platform     = :ios, "9.0"

  s.source       = { :git => "https://github.com/react-native-community/react-native-clipboard", :tag => "#{s.version}" }
  s.source_files  = "ios/**/*.{h,m}"

  s.dependency 'React'
end

**Comment by kenMarquez** [comment]
i'm recently start to have the same problem, i'm using RN 0.60.5

![image](https://user-images.githubusercontent.com/10731555/72747916-8a910f00-3b7b-11ea-9f2d-174c1c2339d9.png)

**Comment by Naturalclar** [comment]
@jiandaoshou-adwald @kenMarquez 
Just published v1.0.0 that fixes this issue.
Note the rename of package from `@react-native-community/react-native-clipboard` to `@react-native-community/clipboard`
