### ISSUE TITLE
build.gradle file is missing.

### ISSUE THREAD

**Issue by tourze** [react-native-community/react-native-clipboard#7]
## Environment

Environment:
  OS: macOS 10.14.5
  Node: 11.9.0
  Yarn: 1.13.0
  npm: 6.9.0
  Watchman: 4.9.0
  Xcode: Xcode 10.2.1 Build version 10E1001
  Android Studio: 3.4 AI-183.6156.11.34.5692245

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.4 => 0.55.4

## Platforms
Android 

## Description
I found that build.gradle file is missing, so the gradle sync failed.

**Comment by Naturalclar** [comment]
@tourze Fixed this issue with release of v1.0.0
